// Builds the shipped x-modal script (exception x-modal, docs/webflow/interactions.md) from its single
// source, src/ix/xModal.ts: bundles it and minifies it into one classic inline script (no
// dependency). Output: docs/webflow/custom-code/x-modal.html (About page footer code) and
// x-modal-head.html (its reduced-motion CSS, About page head code).
// Usage: node scripts/build-x-modal.mjs [--check]   (--check fails if the file is out of date)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { build } from "vite";

const OUT = "docs/webflow/custom-code/x-modal.html";
const HEAD_OUT = "docs/webflow/custom-code/x-modal-head.html";
const CSS_SRC = "src/styles/exceptions/x-modal.css";

const { output } = (
  await build({
    configFile: false,
    logLevel: "silent",
    build: {
      write: false,
      minify: true,
      target: "es2022",
      lib: { entry: "scripts/x-modal-entry.ts", formats: ["iife"], name: "xModal", fileName: "x-modal" },
      // Vite keeps whitespace in library output; Rolldown's own minifier strips it.
      rolldownOptions: { output: { minify: { compress: true, mangle: true, codegen: { removeWhitespace: true } } } },
    },
  })
)[0];

const code = output[0].code.trim();
const html = `<!-- x-modal: the shared modal (first use: About, founder bios). Page footer custom code of the About page only for now (if another page starts using it, move it to site-wide footer code), see docs/webflow/interactions.md. GENERATED by scripts/build-x-modal.mjs from src/ix/xModal.ts: never edit by hand. No dependency. The pasted source is the <script> block only. -->
<script>${code}</script>
`;

/* The CSS part (reduced motion): minified, tokens renamed for the Webflow variables. */
const css = readFileSync(CSS_SRC, "utf8")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/var\(--([\w-]+)\)/g, "var(--_flint---$1)")
  .replace(/\s+/g, " ")
  .replace(/\s*([{}:;,>])\s*/g, "$1")
  .replace(/;}/g, "}")
  .replace(/\(([\w-]+):/g, "($1:")
  .trim();
const headHtml = `<!-- x-modal (CSS part): the modal opens and closes at once under prefers-reduced-motion. Page HEAD custom code of the About page only for now (if another page starts using it, move it to site-wide head code), see docs/webflow/interactions.md. GENERATED by scripts/build-x-modal.mjs from ${CSS_SRC}: never edit by hand. -->
<style>${css}</style>
`;

const files = [
  [OUT, html],
  [HEAD_OUT, headHtml],
];
if (process.argv.includes("--check")) {
  const stale = files.filter(([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content);
  if (stale.length) {
    console.error(`${stale.map(([path]) => path).join(", ")} out of date: run node scripts/build-x-modal.mjs`);
    process.exit(1);
  }
  console.log(`up to date (script ${code.length} characters, head style ${css.length})`);
} else {
  files.forEach(([path, content]) => writeFileSync(path, content));
  console.log(`script ${code.length} characters, head style ${css.length}`);
}
